function getPageContent() {
  return {
    home: {
      title: "Home",
      intro: "Kickstart your Angular app with a consistent structure and best practices.",
      sections: [
        { title: "Getting Started", body: "Use the navbar to explore About, Dashboard, and Profile pages." },
        { title: "Tech Stack", body: "Angular + Router; UI via Material/Bootstrap/Tailwind/PrimeNG." }
      ]
    },
    about: {
      title: "About",
      intro: "This project was generated by Polyfront-Scaffold.",
      sections: [
        { title: "Goals", body: "Speed, consistency, and scalable architecture guided by SOLID principles." },
        { title: "Extensibility", body: "Adapter/Factory patterns allow pluggable UI frameworks." }
      ]
    },
    dashboard: {
      title: "Dashboard",
      intro: "A simple place to surface metrics and quick actions.",
      sections: [
        { title: "Metrics", body: "Hook in your API to show real data here." },
        { title: "Next Steps", body: "Add widgets and charts using your UI library of choice." }
      ]
    },
    profile: {
      title: "Profile",
      intro: "Manage your account and preferences.",
      sections: [
        { title: "Identity", body: "Display and edit basic user information." },
        { title: "Preferences", body: "Theme, language, and notification settings." }
      ]
    }
  };
}

module.exports = { getPageContent };