name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run pack:dry
      - name: Scaffold (Vite TS + MUI)
        run: node ./bin/index.js ci-app --framework react-vite --ts --ui mui --store none --test-unit vitest --test-e2e none
      - name: Build & test scaffold
        working-directory: Frontends/React/Vite/ci-app
        run: |
          npm ci
          npm run build
          npm test --if-present

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
