name: CI & Verify Scaffold Matrix

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build & Test Scaffold Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 22]
        framework: [react-vite] # extend later: react-webpack, angular

    env:
      APP_NAME: ci-app
      UI: mui
      STORE: none
      UNIT_TEST: vitest
      E2E_TEST: none

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Make CLI executable (non-Windows)
        if: runner.os != 'Windows'
        run: chmod +x bin/index.js

      - name: Scaffold app
        run: |
          node ./bin/index.js "$APP_NAME" \
            --framework=${{ matrix.framework }} \
            --ts \
            --ui=$UI \
            --store=$STORE \
            --test-unit=$UNIT_TEST \
            --test-e2e=$E2E_TEST \
            --root=Frontends \
            --on-exists=overwrite
        shell: bash

      - name: Resolve generated app directory
        run: |
          case "${{ matrix.framework }}" in
            react-vite) EXPECTED="Frontends/React/Vite/$APP_NAME" ;;
            react-webpack) EXPECTED="Frontends/React/Webpack/$APP_NAME" ;;
            angular) EXPECTED="Frontends/Angular/$APP_NAME" ;;
            *) EXPECTED="" ;;
          esac

          if [ -d "$EXPECTED" ]; then
            echo "APP_DIR=$EXPECTED" >> $GITHUB_ENV
          else
            FOUND=$(find . -type d -name "$APP_NAME" -not -path "*/node_modules/*" -print -quit)
            if [ -n "$FOUND" ]; then
              echo "APP_DIR=$FOUND" >> $GITHUB_ENV
            else
              echo "❌ Could not locate generated app directory"
              exit 1
            fi
          fi
        shell: bash

      - name: Verify app directory exists
        run: test -d "${APP_DIR}" || (echo "❌ ${APP_DIR} not found"; exit 1)
        shell: bash

      - name: Install app dependencies
        run: npm ci
        working-directory: ${{ env.APP_DIR }}

      - name: Lint (optional)
        run: npm run -s lint || echo "no lint script"
        working-directory: ${{ env.APP_DIR }}

      - name: Unit tests (optional)
        run: npm test --silent || echo "no tests or none selected"
        working-directory: ${{ env.APP_DIR }}

      - name: Build
        run: npm run -s build
        working-directory: ${{ env.APP_DIR }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  verify-fast-matrix:
    name: Verify Scaffold Matrix (Fast)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm i -D vite vitest webpack webpack-cli jest @angular/cli typescript jsdom
      - name: Run full matrix verification (parallel + fast)
        env:
          PF_MATRIX: full
          PF_CONCURRENCY: '6'
          PF_FAST: fw-lang-first
          PF_ORDER: react-vite,react-webpack,angular
          PF_UI_ORDER: mui,bootstrap,tailwind,antd,chakra
          PF_LANGS: ts,js
          PF_ON_EXISTS: rename
        run: node scripts/verify-once.js

